In [1]:
%cd ..

/Users/macos/Uni/1st_year/IntroDS/mini_project

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
plt.style.use('seaborn-v0_8')
plt.rcParams.update({'font.size': 8})

## Examine processed data

In [4]:
path = "data/data_merged_int.xlsx"

df_proc = pd.read_excel(path)

In [5]:
df_proc.head()

,Entity,Year,gdp_growth,gdp_per_capita,Electricity from renewables (TWh),Capacity(MW),Investment(USDmn)
0,Afghanistan,2011,0.426355,591.190030,0.60,244.92,28.69
1,Afghanistan,2012,12.752287,638.845852,0.74,271.47,62.62
2,Afghanistan,2013,5.600745,624.315454,0.89,293.64,268.46
3,Afghanistan,2014,2.724543,614.223342,1.00,298.61,6.94
4,Afghanistan,2015,1.451315,556.007221,1.03,302.63,4.89

In [6]:
df_af = df_proc[df_proc['Entity'] == 'Afghanistan']

-0.030206304276668962

In [24]:
s1, s2 = 'gdp_growth', 'gdp_per_capita'
t1, t2, t3 = 'Electricity from renewables (TWh)', 'Capacity(MW)', 'Investment(USDmn)'

def pearson(df):
    return {
        'corr_gdpg_erenewable': np.corrcoef(df[s1], df[t1])[0, 1],
        'corr_gdpg_capacity': np.corrcoef(df[s1], df[t2])[0, 1],
        'corr_gdpg_investment': np.corrcoef(df[s1], df[t3])[0, 1],
        'corr_gdp_erenewable': np.corrcoef(df[s2], df[t1])[0, 1],
        'corr_gdp_capacity': np.corrcoef(df[s2], df[t2])[0, 1],
        'corr_gdp_investment': np.corrcoef(df[s2], df[t3])[0, 1]
    }

s_pearson = df_proc.groupby('Entity').apply(pearson)

/Users/macos/miniforge3/envs/introds/lib/python3.9/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/macos/miniforge3/envs/introds/lib/python3.9/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/macos/miniforge3/envs/introds/lib/python3.9/site-packages/numpy/lib/function_base.py:2889: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/Users/macos/miniforge3/envs/introds/lib/python3.9/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/Users/macos/miniforge3/envs/introds/lib/python3.9/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

In [33]:
df_pearson = pd.DataFrame(s_pearson.values.tolist(), index=s_pearson.index)

In [37]:
df_pearson.head()

,corr_gdpg_erenewable,corr_gdpg_capacity,corr_gdpg_investment,corr_gdp_erenewable,corr_gdp_capacity,corr_gdp_investment
Entity,,,,,,
Afghanistan,-0.030206,-0.399820,0.359323,-0.329196,-0.846422,0.431143
Albania,0.237024,-0.598811,-0.122495,0.100881,0.003094,-0.359180
Algeria,-0.606038,-0.673677,0.559440,-0.414295,-0.749111,0.628588
Angola,-0.805716,-0.547269,-0.315302,-0.898201,-0.510064,-0.149281
Antigua and Barbuda,-0.542768,-0.618756,0.138805,0.450548,0.474978,0.119196

In [36]:
df_pearson = df_pearson.dropna()

In [42]:
df_pearson.describe()

,corr_gdpg_erenewable,corr_gdpg_capacity,corr_gdpg_investment,corr_gdp_erenewable,corr_gdp_capacity,corr_gdp_investment
count,171.000000,1.710000e+02,1.710000e+02,171.000000,171.000000,171.000000
mean,-0.432867,-2.300389e-01,8.462264e-02,0.314653,0.159085,-0.006273
std,0.464051,3.917160e-01,2.530820e-01,0.631394,0.470462,0.278701
min,-1.000000,-1.000000e+00,-7.030618e-01,-0.932584,-0.846422,-0.927854
25%,-0.872115,-5.164564e-01,-6.265434e-17,-0.231248,-0.046049,-0.146598
50%,-0.496285,-1.727042e-01,4.858935e-02,0.418434,0.108753,0.000000
75%,-0.098955,1.028220e-16,2.305009e-01,0.981399,0.508490,0.154525
max,0.642999,8.112029e-01,8.356256e-01,1.000000,1.000000,0.947975